<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProtoFact.Abstractions\ProtoFact.Abstractions.csproj" />
    <ProjectReference Include="..\ProtoFact.Domain\ProtoFact.Domain.csproj" />
    <ProjectReference Include="..\ProtoFact.Engine\ProtoFact.Engine.csproj" />
  </ItemGroup>

</Project>
